version: '2.4'

services:
  node-hello:
    build:
      context: ./
      dockerfile: Dockerfile.node-hello
    image: node-hello
    stop_signal: SIGKILL

  arch-detector:
    build:
      context: ./
      dockerfile: Dockerfile.arch-detector
    image: arch-detector
    stop_signal: SIGKILL
